name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "PATH=$HOME/.fly/bin:$PATH" >> $GITHUB_ENV
      - name: Debug PATH
        run: |
          echo "DEBUG PATH=$PATH"
          echo "Contents of /home/runner/.fly/bin:"
          ls -l /home/runner/.fly/bin
      - name: Authenticate Fly
        run: flyctl auth login --access-token ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy to Fly
        run: flyctl deploy --config fly.toml --remote-only --strategy immediate
