name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "export PATH=$HOME/.fly/bin:$PATH" >> $GITHUB_ENV
      - name: Authenticate Fly
        run: |
          source $GITHUB_ENV
          flyctl auth login --token ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy to Fly
        run: |
          source $GITHUB_ENV
          flyctl deploy --config fly.toml --remote-only --strategy immediate
